version: '3.7'
services:

  waitfordb:
    build:
      context: ./wait-for-dependencies
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    command: postgres:5432

  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5433:5432"
    logging:
      options:
        max-size: 10m
        max-file: "3"

  scheduler:
    image: apache/airflow:2.0.0b1-python3.8
    restart: always
    depends_on:
      - postgres
      - webserver
      - waitfordb
    env_file:
      - .env
    ports:
      - "8793:8793"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./airflow-logs:/opt/airflow/logs
    command: ["scheduler"]
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  webserver:
    image: apache/airflow:2.0.0b1-python3.8
    hostname: webserver
    restart: always
    depends_on:
      - postgres
      - waitfordb
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./airflow-logs:/opt/airflow/logs
      - ./config/airflow.cfg:${AIRFLOW_HOME}/airflow.cfg
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "8080:8080"
    entrypoint: ./scripts/airflow-entrypoint.sh
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3